sudo: required
language: python
#cache: pip
services:
  - docker
install:
  - pip install molecule==1.25.0
  - pip install docker
script:
  - molecule syntax
  - molecule create
  - molecule converge
  - molecule idempotence
  - molecule verify
#before_deploy:
#  - git config --global user.email "builds@travis-ci.com"
#  - git config --global user.name "CI"
#  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
#  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#  - git push -q https://$TAGPERM@github.com/org/repo --tags
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  skip_cleanup: true
#  on:
#    tags: false
#    branch: master
#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
